In [1]:
!pip install pandas

Requirement already satisfied: pandas in d:\Behaviour analysis of customers\venv\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in d:\Behaviour analysis of customers\venv\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\Behaviour analysis of customers\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\Behaviour analysis of customers\venv\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in d:\Behaviour analysis of customers\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

df = pd.read_csv('netflix_titles.csv')

In [9]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [5]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [7]:
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [12]:
df['id'] = 1

In [13]:
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country'] = df['country'].fillna('Unknown')

In [18]:
df = pd.read_csv("netflix_titles.csv")

# Split the country column by comma
df['country'] = df['country'].str.split(',')

# Convert one row into multiple rows
df = df.explode('country')

# Remove extra spaces
df['country'] = df['country'].str.strip()

# Reset index
df = df.reset_index(drop=True)

print(df.head())

  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season
3  September 24, 2021          2021  TV-MA   1 Season
4  September 24, 2021          2021  TV-MA  2 Seasons

                                           listed_in  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                         description
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...

In [20]:
df = pd.read_csv("netflix_titles.csv")

# Split the country column by comma
df['director'] = df['director'].str.split(',')

# Convert one row into multiple rows
df = df.explode('director')

# Remove extra spaces
df['director'] = df['director'].str.strip()

# Reset index
df = df.reset_index(drop=True)
print(df.head())

  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season
3  September 24, 2021          2021  TV-MA   1 Season
4  September 24, 2021          2021  TV-MA  2 Seasons

                                           listed_in  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                         description
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...

In [14]:
!pip install sqlalchemy
!pip install pymysql
!pip install mysql-connector-python
!pip install cryptography

Requirement already satisfied: sqlalchemy in d:\Behaviour analysis of customers\venv\Lib\site-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in d:\Behaviour analysis of customers\venv\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\Behaviour analysis of customers\venv\Lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: pymysql in d:\Behaviour analysis of customers\venv\Lib\site-packages (1.1.2)
Requirement already satisfied: mysql-connector-python in d:\Behaviour analysis of customers\venv\Lib\site-packages (9.6.0)
Requirement already satisfied: cryptography in d:\Behaviour analysis of customers\venv\Lib\site-packages (46.0.6)
Requirement already satisfied: cffi>=2.0.0 in d:\Behaviour analysis of customers\venv\Lib\site-packages (from cryptography) (2.0.0)
Requirement already satisfied: pycparser in d:\Behaviour analysis of customers\venv\Lib\site-packages (from cffi>=2.0.0->cryptography) (3.0)

In [21]:
import mysql.connector
from sqlalchemy import create_engine

# MySQL connection
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="mysql@123",
    database="customer_behaviour"
)

cursor = conn.cursor()
print("Connected")

# SQLAlchemy engine
engine = create_engine("mysql+pymysql://root:mysql%40123@localhost/customer_behaviour")

print("Engine created")

df.to_sql("netflix_data", engine, if_exists="replace", index=False)

print("Data uploaded to MySQL successfully")

Connected
Engine created
Data uploaded to MySQL successfully